version: 2

jobs:
    build:
        environment:
            - AWS_USER: "ec2-user"
            - AWS_DEST: "/var/www/html/"
        machine:
            enabled: true
        node:
            version: 8.10.0
        timezone:
            America/Los_Angeles
        branches:
            only:
                - dev
                - master
        steps:
            - checkout
            - run:
                name: Node version
                command: node --version
            - run:
                name: NPM version
                command: npm --version
            # - run:
            #     name: Trash node_modules
            #     command: rm -rf node_modules
            - run:
                name: Rebuild node-sass
                command: npm rebuild node-sass
            - run:
                name: Clutch Bootstrap
                command: npm run bootstrap
    deploy-staging:
        machine:
            enabled: true
        steps:
            - run:
                name: Staging Deploy ( dev branch )
                command: npm run deploy:staging
    deploy-production:
        machine:
            enabled: true
        steps:
            - run:
                name: Production Deploy ( master branch )
                command: npm run deploy:production

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy-staging:
                requires:
                    - build
                filters:
                    branches:
                        only: dev
            - deploy-production:
                requires:
                    - build
                filters:
                    branches:
                        only: master
