version: 2

jobs:
    build:
        working_directory: ~/clutch
        machine:
            enabled: true
        steps:
            - checkout
            - run:
                name: Node version
                command: node --version
            - run:
                name: NPM version
                command: npm --version
            - run:
                name: Clutch Bootstrap
                command: npm run bootstrap
            - run:
                name: Clutch build
                command: npm run build
            - persist_to_workspace:
                root: ~/clutch
                paths:
                    - .
    deploy-dev:
        working_directory: ~/clutch
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: ~/clutch
            - run:
                name: Development Deploy ( dev branch )
                command: export NODE_ENV=dev ; npm run deploy
    deploy-prod:
        working_directory: ~/clutch
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: ~/clutch
            - run:
                name: Production Deploy ( master branch )
                command: export NODE_ENV=prod ; npm run deploy

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy-dev:
                requires:
                    - build
                filters:
                    branches:
                        only: dev
            - deploy-prod:
                requires:
                    - build
                filters:
                    branches:
                        only: master
